---
- name: Start irods testing environment
  delegate_to: localhost
  community.docker.docker_compose_v2:
    project_name: ibridges_irods_test
    project_src: ../files

- name: Install ibridges
  ansible.builtin.pip:
    name: ibridges

- name: Create testfiles
  ansible.builtin.copy:
    dest: /tmp/test/testfiles
    src: ./

- name: Create download test destination
  ansible.builtin.file:
    path: /home/synctest/testfiles
    state: directory

- name: Upload testfiles
  uusrc.ibridges_upload:
    env:
      irods_host: irods-catalog-provider # container name
      irods_port: 1247
      irods_user_name: rods
      irods_default_resource: "demoResc"
      irods_home: /tempZone/home/rods
      irods_zone_name: tempZone
    irods_path: "~/"
    local_path: "/tmp/test/testfiles/"
    password: rods
  retries: 10
  delay: 5 # retry because irods server might not be available yet

- name: Add new testfile for sync test
  ansible.builtin.copy:
    dest: /tmp/test/testfiles/penguin.txt
    content: sweet animal
