version: '3'
networks:
  common_network:
    name: irods_test_network
    external: true
services:
  irods-catalog:
    image: irods-catalog
    networks:
      - common_network
    build:
        context: ../../docker/irods_catalog
    environment:
        - POSTGRES_PASSWORD=testpassword
  irods-catalog-provider:
    image: irods-catalog-provider
    networks:
      - common_network
    build:
        context: ../../docker/irods_catalog_provider
    depends_on:
        - irods-catalog
