---
- name: iBridges Sync ResearchCloud Component
  hosts: localhost
  vars:
    _ibridges_paths: "{{ ibridges_irods_path.split(',') }}"
    _ibridges_user_from_path: "{{ ibridges_target_path | regex_search('^\/home\/(\\w+)(\/\\w*)?', '\\1') | default([''], true) | first }}"
    _ibridges_user: "{{ ibridges_user | default(_ibridges_user_from_path, true) | default('root', true) }}"
    _ibridges_group: "{{ ibridges_group | default(_ibridges_user, true) | default('root', true) }}"
    _ibridges_custom_pip_location: /tmp/irods_component/pip_dependencies

  tasks:
    - name: Install iBridges
      ansible.builtin.pip:
        name: ibridges~=1.0
        extra_args: "--target {{ _ibridges_custom_pip_location }}"
      tags: molecule-idempotence-notest

    - name: Create target directory if it does not exist
      ansible.builtin.file:
        path: "{{ ibridges_target_path }}/{{ item | basename }}"
        state: directory
        mode: "0750"
        owner: "{{ _ibridges_user }}"
        group: "{{ _ibridges_group }}"
      with_items: "{{ _ibridges_paths }}"

    - name: iBridges sync
      uusrc.ibridges.ibridges_sync:
        mode: down
        env: '{{ ibridges_env | regex_replace("\\", "") | from_yaml }}' # this is a bit hackish: the component parameter expects JSON, ResearchCloud will then strip the double-quotes from this parameter, turning it into valid YAML...
        irods_path: "{{ ibridges_irods_path }}"
        local_path: "{{ ibridges_target_path }}/{{ item | basename }}"
        password: "{{ ibridges_password }}"
      check_mode: "{{ ibridges_dry_run | default(false) | bool }}"
      with_items: "{{ _ibridges_paths }}"
      environment:
        PYTHONPATH: "{{ _ibridges_custom_pip_location ~ ':' ~ ansible_env.PYTHONPATH if ansible_env['PYTHONPATH'] is defined else _ibridges_custom_pip_location }}"
  
    - name: Change permissions of downloaded files
      ansible.builtin.file:
        path: "{{ ibridges_target_path }}/{{ item | basename }}"
        state: directory
        recurse: true
        mode: "0750"
        owner: "{{ _ibridges_user }}"
        group: "{{ _ibridges_group }}"
      with_items: "{{ _ibridges_paths }}"
