- name: Test ibridges module
  hosts: localhost
  vars_prompt:
    - name: password
      prompt: Enter iRODS password
    - name: env_file
      prompt: Enter absolute path to irods environment file
      private: false
    - name: irods_path
      prompt: Enter path to copy from irods
      private: false
    - name: local_path
      prompt: Enter path to copy to locally
      private: false

  tasks:
  - name: Download testdata to localhost
    ibridges:
      state: present
      env_file: "{{ env_file }}"
      irods_path: "{{ irods_path }}"
      local_path: "{{ local_path }}"
      password: "{{ password }}"
