---
- name: Cleanup
  hosts: all
  gather_facts: false
  tasks:
    # - name: Stop irods testing environment
    #   delegate_to: localhost
    #   community.docker.docker_compose:
    #     project_name: ibridges_irods_test
    #     state: absent
