---
driver:
  name: docker
provisioner:
  name: ansible
platforms:
  - name: ibridges-ubuntu22
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    pre_build_image: true
    networks:
      - name: irods_test_network
