---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Start irods testing environment
      delegate_to: localhost
      community.docker.docker_compose_v2:
        project_name: ibridges_irods_test
        project_src: ../files/

    - name: Install ibridges
      ansible.builtin.pip:
        name: ibridges
  
    - name: Create testfiles
      ansible.builtin.copy:
        dest: /tmp/test/testfiles
        src: ./

    - name: Create download test destination
      ansible.builtin.file:
        path: /home/rods/testfiles
        state: directory

