password = "test"
server_version = "4.2.12"
can_write_pam_pass = false
create_session_from_cached_pw = false
resources = ["demoResc", "dev001", "dev001_1", "dev001_2", "dev001_p1", "dev001_p2", "dev002", "dev002_1", "dev002_p1", "dev003", "dev003_1", "dev003_p1", "irodsResc", "irodsRescRepl", "irodsRescReplS3"]
free_resources = [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]
test_user = "researcher"
test_user_pw = "test"
ticket_date_only = true
