---
name: Run ansible-test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  molecule:
    name: molecule
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ansible:
          - stable-2.9
          - stable-2.17
        python:
          - 3.8
          - 3.9
          - 3.11
          - 3.12
        exclude:
          - python: 3.9
          - ansible: stable-2.9
          - python: 3.11
          - ansible: stable-2.9
          - python: 3.12
          - ansible: stable-2.9
    steps:

      - name: Perform sanity testing with ansible-test
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          ansible-core-version: '${{ matrix.ansible }}'
          testing-type: sanity
          target-python-version: '${{ matrix.python }}'
