---
name: Run component tests against iRODS
on:
  pull_request:
    paths:
      - 'component.yml'
      - 'molecule/component/**'
  push:
    paths:
      - 'component.yml'
      - 'molecule/component/**'
    branches:
      - main

jobs:
  molecule:
    runs-on: ubuntu-latest
    if: |
      ${{ ! contains(github.event.head_commit.message, '#nointegrationtests') &&
            ( github.event_name == 'push' ||
              github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name
            )
       }}
    env:
      ANSIBLE_FORCE_COLOR: '1'
      ANSIBLE_STDOUT_CALLBACK: yaml
      REQUIREMENTS_FILE: molecule/ext/requirements.txt
      MOLECULE_CONFIG: molecule/ext/molecule.yml
      ANSIBLE_REQUIREMENTS_FILE: molecule/ext/requirements.yml
      DRIVER: docker
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r ${{ env.REQUIREMENTS_FILE }}
      - run: ansible-galaxy install -r requirements.yml
      - run: ansible-galaxy install -r ${{ env.ANSIBLE_REQUIREMENTS_FILE }}
      - run: git clone https://github.com/iBridges-for-iRODS/iBridges.git ibridges && mv ibridges/docker ./docker
      - name: Run molecule tests
        run: molecule -vvv -c ${{ env.MOLECULE_CONFIG }} test -s component
