---
name: Run integration tests against iRODS
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  molecule:
    runs-on: ubuntu-latest
    if: |
      ${{ ! contains(github.event.head_commit.message, '#nointegrationtests') &&
            ( github.event_name == 'push' ||
              github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name
            )
       }}
    env:
      ANSIBLE_FORCE_COLOR: '1'
      ANSIBLE_STDOUT_CALLBACK: yaml
      REQUIREMENTS_FILE: molecule/requirements.txt
    strategy:
      fail-fast: false
      matrix:
        python:
          - '3.12'
          - '3.10'
        ansible:
          - 2.9
          - 9.6.1
        exclude:
          - ansible: 2.9
            python: '3.12'
          - ansible: 9.6.1
            python: '3.10'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - run: git clone https://github.com/iBridges-for-iRODS/iBridges.git ibridges && mv ibridges/docker ./docker
      - run: pip install -U ansible==${{ matrix.ansible }}
      - run: pip install -r ${{ env.REQUIREMENTS_FILE }}
      - run: ansible-galaxy install -r requirements.yml
      - name: Run molecule tests
        run: molecule -vvv test
